### ISSUE TITLE
Retrieving package VDF data returns binary VDF

### ISSUE THREAD

**Issue by Jleagle** [Philipp15b/go-steam#100]
Hi, I am trying to get the VDF data on apps and packages.
The app proto `CMsgClientPICSProductInfoResponse_AppInfo` seems to always return okay but  trying to get the VDF data from a package `CMsgClientPICSProductInfoResponse_PackageInfo` always returns binary VDF.
Is there a helper somewhere to convert to text?
Thanks.

**Comment by Philipp15b** [comment]
`go-steam` does not yet contain a VDF parser. Some years ago, @marshauf wrote a VDF parser: see #21. 

SteamKit also has an implementation: https://github.com/SteamRE/SteamKit/blob/aa3e7f1750644286a8f4ee144992f80d157b1f71/SteamKit2/SteamKit2/Types/KeyValue.cs#L218.

I would be very happy to accept a keyvalue/vdf related pull request!

**Comment by Jleagle** [comment]
Thanks for the heads up on github.com/marshauf/keyvalues, the only other package i came across was github.com/BenLubar/vdf. Both have tests that pass, but the key value structs they created were not actually correct. I ended up porting the binary VDF reader in SteamKit over to a new repo at github.com/Jleagle/valve-data-format-go.

**Comment by mjsir911** [comment]
I'm a bit confused, looking at these repositories they all seem to be parsing the same kind of data, but is there any difference between valve's `acf` (how the appmanifests are stored on my machine) and the discussed `vdf` data?

I don't see any "binary" values anywhere that are spoken of.

**Comment by Jleagle** [comment]
> I'm a bit confused, looking at these repositories they all seem to be parsing the same kind of data, but is there any difference between valve's `acf` (how the appmanifests are stored on my machine) and the discussed `vdf` data?
> 
> I don't see any "binary" values anywhere that are spoken of.

From my limited experience, app data is sent to the steam client as text and package data is sent over as binary.
