### ISSUE TITLE
gs-bot returns connection failure on successful connection

### ISSUE THREAD

**Issue by Nexure** [Philipp15b/go-steam#112]
When attempting to connect using the gs-bot the connection to the steam can be established using a random server, but the [connect function](https://github.com/Philipp15b/go-steam/blob/master/gsbot/gsbot.go#L140) returns false, even though the successful connection was made. While looking, I assume a simple fix to this issue could be just returning true, as it does so below?

**Comment by Philipp15b** [comment]
Good catch! The function is definitely confusing. I think the original intent was to indicate by the Boolean whether `listPath` was used or not, not whether there was an error. I think that should be removed completely. Also, the result of `s.bot.Client.Connect()` (possibly an error) is completely ignored.

I would be happy to accept a pull request to fix that!
