### ISSUE TITLE
Update generator for new protoc and protoc-gen-go

### ISSUE THREAD

**Issue by Philipp15b** [Philipp15b/go-steam#118]
See https://github.com/Philipp15b/go-steam/pull/117#issuecomment-827002980 and https://github.com/Philipp15b/go-steam/pull/117#issuecomment-827126492. The generator relies on an an ancient version of `protoc-gen-go`. 

With a current version, `protoc-gen-go` errors:
```
 protoc-gen-go: unable to determine Go import path for "google/protobuf/descriptor.proto"
>
> Please specify either:
>       • a "go_package" option in the .proto source file, or
>       • a "M" argument on the command line.
>
> See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
>
> --go_out: protoc-gen-go: Plugin failed with status code 1.
> exit status 1
```

The generator code (`generator.go`) needs to be updated to pass the "M" argument on the command line.

**Comment by Tommy-42** [comment]
I opened #120 to fix this issue, If someone have a working project that want to test it out, that would be great
