### ISSUE TITLE
client.Connect() timeout

### ISSUE THREAD

**Issue by tangbo1430** [Philipp15b/go-steam#131]
func main() {
	myLoginInfo := new(steam.LogOnDetails)
	myLoginInfo.Username = "Your username"
	myLoginInfo.Password = "Your password"

	client := steam.NewClient()
	client.Connect()
	for event := range client.Events() {
		switch e := event.(type) {
		case *steam.ConnectedEvent:
			client.Auth.LogOn(myLoginInfo)
		case *steam.MachineAuthUpdateEvent:
			ioutil.WriteFile("sentry", e.Hash, 0666)
		case *steam.LoggedOnEvent:
			client.Social.SetPersonaState(steamlang.EPersonaState_Online)
		case steam.FatalErrorEvent:
			log.Print(e)
		case error:
			log.Print(e)
		}
	}
}

![image](https://user-images.githubusercontent.com/62140113/189266011-f5988954-b62c-4f55-bb1d-ef055cb6715a.png)

**Comment by tangbo1430** [comment]
> func main() { myLoginInfo := new(steam.LogOnDetails) myLoginInfo.Username = "Your username" myLoginInfo.Password = "Your password"
> 
> ```
> client := steam.NewClient()
> client.Connect()
> for event := range client.Events() {
> 	switch e := event.(type) {
> 	case *steam.ConnectedEvent:
> 		client.Auth.LogOn(myLoginInfo)
> 	case *steam.MachineAuthUpdateEvent:
> 		ioutil.WriteFile("sentry", e.Hash, 0666)
> 	case *steam.LoggedOnEvent:
> 		client.Social.SetPersonaState(steamlang.EPersonaState_Online)
> 	case steam.FatalErrorEvent:
> 		log.Print(e)
> 	case error:
> 		log.Print(e)
> 	}
> }
> ```
> 
> }
> 
> ![image](https://user-images.githubusercontent.com/62140113/189266011-f5988954-b62c-4f55-bb1d-ef055cb6715a.png)

**Comment by k0mar12** [comment]
@tangbo1430 How did u fix it? Thanks

**Comment by 5133n** [comment]
> @tangbo1430 How did u fix it? Thanks

```go
client := steam.NewClient()
steam.InitializeSteamDirectory() //<----- add this
client.Connect()
```

**Comment by k0mar12** [comment]
> > @tangbo1430 How did u fix it? Thanks
> 
> ```go
> client := steam.NewClient()
> steam.InitializeSteamDirectory() //<----- add this
> client.Connect()
> ```

Yep, thanks, i have already found it :)
