### ISSUE TITLE
SteamApps

### ISSUE THREAD

**Issue by marshauf** [Philipp15b/go-steam#21]
Hello,

I just want to let you know that I am working on the SteamApps handler.
I got the KeyValue parsing in text and binary form done and uploaded here: https://github.com/marshauf/keyvalues
Would be nice if someone could check it for bugs.
A soon as I got the SteamApps handler working I will create a pull request.

**Comment by Philipp15b** [comment]
I did not test it, but it looks good. Feel free to create a pull request with some Steam API usage.

**Comment by mjsir911** [comment]
For future reference, this key value format seems to go by the filetype `acf` (which is how I was looking for it).
