### ISSUE TITLE
go-steam trade

### ISSUE THREAD

**Issue by TwinkerMan** [Philipp15b/go-steam#39]
Firstly, tradeapi needs steamLoginSecure but trade don't

replace in /trade/trade.go
```
func New(sessionId, steamLogin string, other steamid.SteamId) *Trade {
	return &Trade{
		other,
		false, false,
		time.Unix(0, 0),
		nil,
		tradeapi.New(sessionId, steamLogin, other),
	}
}
```
to
```
func New(sessionId, steamLogin, steamLoginSecure string, other steamid.SteamId) *Trade {
	return &Trade{
		other,
		false, false,
		time.Unix(0, 0),
		nil,
		tradeapi.New(sessionId, steamLogin, steamLoginSecure, other),
	}
}
```

Seconly, trade doesn't work. In Steam client on PC I got network error after RespondRequest(id, true)

Debug results:

request to t.baseUrl+"tradestatus/" returns
```
{"success":false,"error":"missing required parameter"}
```

**Comment by Philipp15b** [comment]
As far as I can see, the first issue should have already been fixed with #23 back in February 2015, no?

Trading should work now with #59.
