### ISSUE TITLE
Is it possible to convert SteamId to SteamId64??

### ISSUE THREAD

**Issue by Gacnt** [Philipp15b/go-steam#43]
When getting trade offers `OtherAccountId`

It returns like a: `STEAM_0:1:31561936`

Is it possible to get a SteamId64 instead like:

`76561198102055159`

Any information would be great thanks looked through the `steamid` package but didn't see anything

**Comment by b1naryth1ef** [comment]
`SteamId.ToUint64()` will give you the uint64 version

**Comment by Gacnt** [comment]
I did that but I only get like a 5 digit number instead of the 17 digit one @b1naryth1ef

**Comment by Gacnt** [comment]
I accomplished this buy doing:

```
accId := value.OtherAccountId.ToUint64()
accId = accId + 76561197960265728
```

which returns the 64 bit steam id
