### ISSUE TITLE
Getting error about cannot UnmarshalJSON when running `tradeoffer.GetOwnInventory`

### ISSUE THREAD

**Issue by Gacnt** [Philipp15b/go-steam#46]
Getting the error:

`cannot unmarshal string into Go value of type []*inventory.Action`

when trying to do:

        ownInv, err := Trader.GetOwnInventory(1, 295110)
        if err != nil {
                log.Println(err)
        }

        log.Println(ownInv)

Not sure exactly what is going on and why it is failing but it is.

**Comment by Philipp15b** [comment]
To debug this, I'd need more data, for example the actual data transferred over the network.
However, I'll just go ahead and hope #59 either fixes this or makes this obsolete :)
