### ISSUE TITLE
Unable to send trade, Error (26)

### ISSUE THREAD

**Issue by Gacnt** [Philipp15b/go-steam#47]
Getting error 26 when trying to create/send a trade offer (according to the enums this means `revoked` which isn't much information).

This is my params:
```
map[sessionid:[fom3oafmo] partner:[76561198102055159] tradeoffermessage:["hi"] json_tradeoffer:[{"me":{"assets":[{"appid":295110,"contextid":1,"amount":1,"assetid":169262651814793732}],"currency":[],"ready":false},"newversion":true,"them":{"assets":[],"currency":[],"ready":false},"version":"3"}] trade_offer_create_params:[{}] serverid:[1] captcha:[]]

{"strError":"There was an error sending your trade offer.  Please try again later. (26)"}
500
2015/09/10 23:27:42 create error: status code not 200
```

I know the assetids are right because they exist in the inventory: http://steamcommunity.com/id/sandboxx/inventory/json/295110/1 if I CTRL+F and find each AssetID individually.

I'm not sure why I'm getting this error 26

**Comment by Philipp15b** [comment]
This should be fixed by #59, hopefully.
