### ISSUE TITLE
So is this package maintained at ALL anymore or not.

### ISSUE THREAD

**Issue by Gacnt** [Philipp15b/go-steam#49]

**Comment by b1naryth1ef** [comment]
Is this package maintained? Yes. Do people have time to help you debug your individual problems, described and reported with minimal information and context? No.

**Comment by Gacnt** [comment]
@b1naryth1ef I have submitted a more than legitimate bug fix for creating trade offers and there has been zero response on it. Don't have to be a dick about it, simple question and going through others issues there is zero response from anybody regarding anything.
