### ISSUE TITLE
Why connect methods os.Exit on error?

### ISSUE THREAD

**Issue by YellowOrWhite** [Philipp15b/go-steam#53]
It is very strange that connect methods do not return error. It is not possible to run multiple concurrent clients when any one of them can just os.Exit whole process. Is there any particular reason for such design?

**Comment by YellowOrWhite** [comment]
One alternative is to emit FatalErrorEvent. It does not break backward compatibility, makes it easier to implement reconnect logic and also removes dependency on log package which is only used in connect methods.

**Comment by Philipp15b** [comment]
Fixed by #51.
