### ISSUE TITLE
Rename internal package

### ISSUE THREAD

**Issue by YellowOrWhite** [Philipp15b/go-steam#57]
Apparantly starting with go 1.4 "internal" package has a special meaning:
https://golang.org/doc/go1.4#internalpackages
Basically it means that you can't import "internal" package and its subpackages from outside.

**Comment by Slacki** [comment]
@Philipp15b I'd like to work on this issue, what should I rename the package "internal" to?

**Comment by Philipp15b** [comment]
@Slacki That'd be great. I'd say "protocol" would be a good name. It describes its contents and shouldn't clash with anything.
