### ISSUE TITLE
Inconsistent usage of types

### ISSUE THREAD

**Issue by YellowOrWhite** [Philipp15b/go-steam#58]
Some simple types, like economy.AssetId, economy.ClassId, economy.InstanceId, tradeoffer.TradeOfferId are used inconsistently. 

For example:
1. In tradeoffer package: TradeOfferId everywhere except for TradeCreateResult struct
2. In tradeoffer package economy types are not used, in inventory package economy types are used.
3. In inventory package: GetOwnInventory takes uint64 instead of ContextId type, but return structs with economy types.
... many more ...

Is economy types and TradeOfferId type really needed? Why not convert them to uint32/uint64?

**Comment by Philipp15b** [comment]
Since you removed those types in #59, I'll consider this fixed.
