### ISSUE TITLE
"fileDescriptor0 redeclared in this block" error

### ISSUE THREAD

**Issue by Slacki** [Philipp15b/go-steam#66]
Described here: https://github.com/golang/protobuf/issues/109
The suggestion is to merge all the files into one. Is it possible here? Any idea what we can do with this?

**Comment by Philipp15b** [comment]
Working with the protocol buffer compiler has been an absolute nightmare during go-steam's development and I really couldn't believe my eyes when I saw it apparently got worse. I'll soon push a fix.

**Comment by Slacki** [comment]
Thank you for this quick fix.
