### ISSUE TITLE
Loggin into Steam account which uses Steam Authenticator

### ISSUE THREAD

**Issue by Slacki** [Philipp15b/go-steam#68]
Can't really log into account which uses this new stuff. Auth codes from Steam Mobile Authenticator are rejected.
https://support.steampowered.com/kb_article.php?ref=8625-WRAH-9030&l=english

The auth codes received by email work like a charm.

**Comment by Philipp15b** [comment]
Has this issue been resolved? Do the auth codes from the Authenticator work?

**Comment by Slacki** [comment]
It works when you pass the code to LogOnDetails.TwoFactorCode.
