### ISSUE TITLE
Error connecting.

### ISSUE THREAD

**Issue by Hexer10** [Philipp15b/go-steam#93]
When I call
```
	myLoginInfo := new(steam.LogOnDetails)
	myLoginInfo.Username = "user"
	myLoginInfo.Password = "pass"

	client := steam.NewClient()
	client.Connect()
```
Sometimes it works but then I get this error:
```
 Error reading from the connection: EOF
```
or sometimes is throws an error on `client.Connect()`:
```
Connect failed: dial tcp 162.254.196.43:27020: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

How can I solve this?

**Comment by Hexer10** [comment]
I tought I've solved this but I'm getting again the errors

**Comment by Nuc1eoN** [comment]
Hey I am also getting an error like this. How can we fix this?
```
Connecting to random server.
Error: Connect failed: dial tcp 208.78.164.11:27019: connect: connection timed out
```

**Comment by Philipp15b** [comment]
Yeah, the IP list needs to be updated periodically. I am happy to accept pull requests for this.

**Comment by Hexer10** [comment]
I don't know if it would cause any issue, but could we just request a new list of IPs everytime the we try to connecting to the steam servers?

**Comment by Nuc1eoN** [comment]
Yeah not sure either, I mean the service list is publicly accessable over the api I linked above.

**Comment by Philipp15b** [comment]
Actually, I think we already have an implementation for fetching the server list: [InitializeSteamDirectory](https://godoc.org/github.com/Philipp15b/go-steam#InitializeSteamDirectory). So a call to this function for the first `Connect()` is also possible.

A simple change [around here](https://github.com/Philipp15b/go-steam/blob/e0f3bb9566e3e26411c596842288faa371e45cec/client.go#L136) to something like
```go
if !steamDirectoryCache.IsInitialized() {
    InitializeSteamDirectory()
}
if steamDirectoryCache.IsInitialized() {
	server = steamDirectoryCache.GetRandomCM()
} else {
	server = GetRandomCM()
}
```
should fix the problem.

**Comment by Philipp15b** [comment]
I've both updated the IP list and added automatic Steam Directory fetching, which should solve the problem. Thanks for the reports!
